# Generated by Django 5.2.5 on 2025-08-29 05:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='api.question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('8df37ed5-77f5-4802-96ad-c32af4a5d420'), verbose_name='ID пользователя'),
        ),
    ]
