# Generated by Django 5.2.5 on 2025-08-30 05:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_answer_question_alter_answer_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('31456895-423d-4192-893d-ac003d28801e'), verbose_name='ID пользователя'),
        ),
    ]
