# Generated by Django 5.2.5 on 2025-08-30 05:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_answer_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='ID пользователя'),
        ),
    ]
